image: 
- Visual Studio 2019
- macos

environment:
  nodejs_version: 12.19.0

install:
- cmd: powershell Install-Product node $env:nodejs_version
- sh: nvm install $nodejs_version
- npm install

test_script:
- node index

build: off
