macos_instance:
  image: big-sur-base
env_task:
  script: brew install node 
  node_modules_cache:
    folder: node_modules
    reupload_on_changes: false # since there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS
      - node --version
    populate_script: 
      - npm install
  test_script: node index
