
module.exports = {
    datas: [
        "http://hawishub.com/page/2",
        "http://hawishub.com/page/3",
        "http://hawishub.com/page/4",
        "http://hawishub.com/page/5",
        "http://hawishub.com/page/6",
        "http://hawishub.com/page/7",
        "http://hawishub.com/page/8",
        "http://hawishub.com/page/9",
        "http://hawishub.com/page/10",
        "http://hawishub.com/page/11",
        "http://tshciewe.com/page/2",
        "http://tshciewe.com/page/3",
        "http://tshciewe.com/page/1",
        "http://tshciewe.com/page/2",
        "http://tshciewe.com/page/3",
        "http://tshciewe.com/page/3",
        "http://tshciewe.com/page/2",
        "http://tshciewe.com/page/2",
        "http://tshciewe.com/page/3",
        "http://tshciewe.com/page/1",
        "http://hawishub.top/page/2",
        "http://hawishub.top/page/2",
        "http://hawishub.top/page/3",
        "http://hawishub.top/page/1",
        "http://blaleela.com/5z10",
        "https://gplinks.co/8B6KBqxi",
    ],
    selector: '.post-title'
}
