name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
        - cron: '*/20 * * * * ' # 每40分钟运行一次
        #- cron: '0 21 * * *' # 每天运行一次

jobs:
  build_on_mac:
    runs-on: macos-10.15  # ubuntu-16.04 macos-10.15 windows-2019
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node index

  build_on_win:
    runs-on: windows-2019  # ubuntu-16.04 macos-10.15 windows-2019
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node index
